### ISSUE TITLE
Missing background color

### ISSUE THREAD

**Issue by codeTrackLift** [codepharm/playground#11]
Create `style` tags in the `head` of `index.html`

Add CSS to change the `background-color` to any color of your choice.

Make a post in the Playground Repo Discussion board. Explain rationale of your color choice in this post.

**Comment by IsthisSid** [comment]
@codeTrackLift please confirm where you want the background-color. Do you want the whole page to have this color?

**Comment by codeTrackLift** [comment]
@IsthisSid please implement background color such that it applies to 100% height and width of the viewport
