### ISSUE TITLE
#44 fit the overflow text on the bottom via media query

### ISSUE THREAD

**Issue by codeByAnnie** [codepharm/playground#46]
Quote by Eleanor Roosevelt isn't aligning with the image properly on certain Mobile devices @IsthisSid

**Comment by IsthisSid** [comment]
@codeByAnnie @codeTrackLift 
For this issue, I used media query to fix/overflow-text on most device dimensions. The only two dimensions it didn't work on are: Samsung Galaxy 8+ and Galaxy Fold. Can one of you guys take a look?

**Comment by IsthisSid** [comment]
#48

**Comment by IsthisSid** [comment]
Linked to pull request #48 - branches have been merged. Close issue.
