### ISSUE TITLE
Link to tackles.html page and add HTML boilerplate

### ISSUE THREAD

**Issue by IsthisSid** [codepharm/playground#72]
- Link to tackles.html page from each page's navbar ('The Daily Tackles' in the dropdown 'Our Adventures')
- Add HTML boilerplate to this page
- Add h1 - "Under Construction" or "Blog coming soon", whichever you think is appropriate for now

**Comment by nettle790** [comment]
May I complete issue #72 also??

**Comment by IsthisSid** [comment]
@nettle790 We are currently working on the content for this page, so @codeByAnnie and I will take this ticket. For now, you can practice on the git practice repo and check back here later.

**Comment by IsthisSid** [comment]
Reviewed and Merged. See PR #83
